/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
	   p.[ProductKey]
      ,p.[ProductAlternateKey] as [Product item code]
      --,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,p.[EnglishProductName] as [Product name]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      ,p.[Color] as [Product color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      ,p.[Size] as [Product size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
      ,p.[ProductLine] as [Product line]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      ,p.[ModelName] as [Model Name]
      --,[LargePhoto]
      ,p.[EnglishDescription] as [Product description]
	  ,ps.EnglishProductSubcategoryName as [Sub category]
	  ,pc.EnglishProductCategoryName as [Product category],
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      --,[StartDate]
      --,[EndDate]
      isnull(p.status, 'OutDate') as [Product status]
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] as p
  left join [AdventureWorksDW2019].[dbo].[DimProductSubcategory] as ps on ps.ProductSubcategoryKey = p.ProductSubcategoryKey
  left join [AdventureWorksDW2019].[dbo].[DimProductCategory] as pc on pc.ProductCategoryKey = ps.ProductCategoryKey
  order by p.ProductKey